
import { GoogleGenAI } from '@google/genai';
import { PerformanceReportData, AgentType, Artifact, Classification, ArtifactType, SessionSchema } from '../types';
import { MOCK_ARTIFACTS } from '../constants';

/**
 * RPR-KONTROL: Gemini Reasoning Bridge (v1.4.0)
 * Authority: GEMINI (The Engineer)
 * Objective: Handle statutory reasoning using hardened VITE env vars.
 */

// Phase 6 Implementation: Browser-safe environment resolution
const API_KEY = import.meta.env.VITE_GEMINI_API_KEY || "";

if (!API_KEY) {
  console.warn("🛡️ SENTINEL: VITE_GEMINI_API_KEY not found. AI features restricted to advisory fallback.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

export const generatePerformanceReport = async (
  sessionId: string,
  projectName: string,
  classification: Classification,
): Promise<PerformanceReportData> => {
  const currentAgentPerformance = [
    { agent: AgentType.GEMINI, taskCompletion: '95%', governanceAdherence: '100%', responseQuality: '9.2/10', autonomyScore: 'High' },
    { agent: AgentType.PERPLEXITY, taskCompletion: '98%', governanceAdherence: '100%', responseQuality: '9.5/10', autonomyScore: 'High' },
    { agent: AgentType.JULES, taskCompletion: '92%', governanceAdherence: '100%', responseQuality: '8.8/10', autonomyScore: 'Medium' },
    { agent: AgentType.COPILOT, taskCompletion: '90%', governanceAdherence: 'N/A', responseQuality: '8.5/10', autonomyScore: 'Low' },
  ];

  const workflowEfficiency = {
    totalInteractions: 47,
    founderInterventions: 3,
    founderInterventionRate: '6.4%',
    escalationsTriggered: 1,
    crossAgentCoordination: 'Excellent',
    bottlenecksIdentified: 'None',
  };

  const flutterSyncStatus = {
    sessionArchived: true,
    artifactsVersioned: true,
    readyForRetrieval: true,
  };

  const artifactsProduced: Artifact[] = MOCK_ARTIFACTS;

  const prompt = `Based on the RPR-KONTROL session for project "${projectName}" (Session ID: ${sessionId}), provide concise recommendations for workflow optimization and agent autonomy improvement. The session had ${workflowEfficiency.totalInteractions} interactions and ${workflowEfficiency.founderInterventions} founder interventions.`;

  let recommendations = "No specific recommendations generated by AI.";
  if (!API_KEY) {
    return {
      summary: {
        agentPerformance: currentAgentPerformance,
        workflowEfficiency: workflowEfficiency,
        artifactsProduced: artifactsProduced,
        recommendations: "API_KEY_MISSING: Gemini service unavailable",
        flutterSyncStatus: flutterSyncStatus,
      },
      markdownReport: markdownReport.replace("## Recommendations", "## Recommendations\n\n⚠️ API_KEY_MISSING: Gemini service unavailable"),
    };
  }
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: prompt,
      config: {
        temperature: 0.7,
        maxOutputTokens: 1000,
      },
    });
    recommendations = response.text || recommendations;
  } catch (error) {
    console.error("Error generating recommendations with Gemini:", error);
    recommendations = "Failed to generate AI recommendations.";
  }

  const date = new Date().toISOString().split('T')[0];

  const markdownReport = `
# RPR-KONTROL Performance Report
**Session ID:** ${sessionId}  
**Project:** ${projectName}  
**Date:** ${date}  
**Classification:** ${classification}

## Agent Performance Summary
| Agent | Task Completion | Governance Adherence | Response Quality | Autonomy Score |
|-------|-----------------|---------------------|------------------|----------------|
${currentAgentPerformance.map(ap => `| ${ap.agent} | ${ap.taskCompletion} | ${ap.governanceAdherence} | ${ap.responseQuality} | ${ap.autonomyScore} |`).join('\n')}

## Workflow Efficiency
- Total interactions: ${workflowEfficiency.totalInteractions}
- Founder interventions: ${workflowEfficiency.founderInterventions} (${workflowEfficiency.founderInterventionRate})
- Escalations triggered: ${workflowEfficiency.escalationsTriggered} (ethical decision)
- Cross-agent coordination: ${workflowEfficiency.crossAgentCoordination}
- Bottlenecks identified: ${workflowEfficiency.bottlenecksIdentified}

## Artifacts Produced
${artifactsProduced.map((artifact, index) => `${index + 1}. ${artifact.type === ArtifactType.DEPLOYMENT ? "Deployment" : artifact.type.charAt(0).toUpperCase() + artifact.type.slice(1)}: ${artifact.title} (${artifact.version}${artifact.uri ? `, ${artifact.uri}` : ''})`).join('\n')}

## Recommendations
${recommendations}

## Flutter Sync Status
✅ Session archived to Firestore  
✅ Artifacts versioned in registry  
✅ Ready for RPR-KONTROL mobile retrieval
`;

  return {
    summary: {
      agentPerformance: currentAgentPerformance,
      workflowEfficiency: workflowEfficiency,
      artifactsProduced: artifactsProduced,
      recommendations: recommendations,
      flutterSyncStatus: flutterSyncStatus,
    },
    markdownReport: markdownReport,
  };
};

/**
 * Generates a high-stakes Forensic Audit Defense Report 
 * when defense_readiness is 'COLLAPSED'.
 */
export const generateAuditDefenseReport = async (session: SessionSchema): Promise<string> => {
  if (!API_KEY) {
    return "SUBSTRATE_UNAVAILABLE: API_KEY_MISSING";
  }
  const prompt = `
    //SENTINEL_PROTOCOL_V1.1.0: EMERGENCY_FORENSIC_RECONSTRUCTION
    AUTHORITY: THE ROOK
    CONTEXT: Statutory Audit Defense (Malaysian Companies Act 2016)
    
    Analyze the following session data and provide a structured, legally-advisory 
    defense report for the Founder.
    
    DATA_INPUT:
    - Session ID: ${session.sessionId}
    - Validation Posture: ${session.dual_state.validation_posture}
    - Performance Metrics: ${JSON.stringify(session.performanceMetrics)}
    - Decisions Log: ${JSON.stringify(session.decisionsLog)}
    
    OUTPUT_STRUCTURE:
    1. //EXECUTIVE_SUMMARY: State of compliance.
    2. //STATUTORY_ANCHORS: Mapping decisions to SSM requirements.
    3. //FORENSIC_VERIFICATION: Proof of agent-founder handshake.
    4. //DEFENSE_RECOMMENDATIONS: Immediate tactical actions.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3-pro-preview',
      contents: prompt,
      config: {
        temperature: 0.2, // Lower temperature for formal advisory output
        maxOutputTokens: 2000,
      },
    });
    return response.text || "Report generation failed.";
  } catch (error) {
    console.error("Error generating Audit Defense Report:", error);
    return "FAILED_TO_GENERATE_FORENSIC_REPORT: Check Sentinel logs.";
  }
};
